#server:
#  port: 8081


dubbo:
  application:
    name: sea-provider-log
  registry:
    protocol: zookeeper
    address: hy.chendahai.cn:2181
  protocol:
    name: dubbo
    port: 20889
  version: 1.0.1
  scan:
    base-packages: com.log