server:
  port: 5051


dubbo:
  application:
    name: sea-consumer-web
  registry:
    protocol: zookeeper
    address: www.chendahai.cn:2181
  protocol:
    name: dubbo
    port: 20551
  version: 1.0.0
  scan:
    base-packages: com.web
  consumer:
    check: false
    timeout: 5000