server:
  port: 8082


dubbo:
  application:
    name: sea-provider-message
  registry:
    protocol: zookeeper
    address: 192.168.1.222:2181
  protocol:
    name: dubbo
    port: 20888
  version: 1.0.0
  scan:
    base-packages: com.message
